sudo: false

language: node_js
node_js:
  - '6'
  - '4'
  - '0.12'
cache:
  directories:
    - node_modules
before_install:
- npm prune
- npm update
after_success: npm run coveralls
notifications:
  webhooks:
    - https://webhooks.gitter.im/e/d763493612da45967361
